apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: ocr-container
          image: faturaacr.azurecr.io/faturayolo-ocr_service:app
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  selector:
    app: ocr
  ports:
    - protocol: TCP
      port: 8001       # Cluster içi erişim portu
      targetPort: 8000 # Container portu
  type: ClusterIP
