apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo-container
          image: faturaacr.azurecr.io/faturayolo-yolo_service:app
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 8002       # Cluster içi erişim portu
      targetPort: 8000 # Container portu
  type: ClusterIP
